# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9c181c781044531ee4075c89abe254cf4d4de98a0615a87c6c3f4fb7d0c62bc0af3a9761948b0cca40cce8a47cd32a1042fb5ec28f2a0965b3d4f96e927bb29

test:
  secret_key_base: f8d044ae464413c61e4cad5a64e8f1440961f0b7c09c7ac6e265b328dd2dff1a93f446ee18223fccf4b9807e07ce89ab22b1e70015f4b3b230ba9e74e3e38728

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
